# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  buildevents: honeycombio/buildevents@0.2.6

executors:
  linuxgo:
    docker:
      - image: golang:1

commands:
  go-build:
    steps:
      ## method 1 to send a command span
      ## the raw buildevents binary is available in the $PATH but requires more arguments
      ## don't use CGO so that this binary can run in alpine-linux containers
      - run: |
          GOOS=linux \
          GOARCH=amd64 \
          CGO_ENABLED=0 \
          buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID go_build -- \
          go build -i -ldflags "-X main.Version=${CIRCLE_BRANCH}" \
          -o $GOPATH/bin/go-discord-bot \
          ./...

jobs:
  setup:
    executor: linuxgo
    steps:
      - buildevents/start_trace
  watch:
    executor: linuxgo
    steps:
      - buildevents/watch_build_and_finish

  test:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            ## method 2 to send a command span
            ## buildevent/berun is a circleci friendly way to create a buildevents command span
            - buildevents/berun:
                bename: go_test
                becommand: go test -v ./...
  build:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - checkout

            - run: go version
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID go_mod_downlaod -- go mod download
            - go-build:

            - run: mkdir -v artifacts; cp -v $GOPATH/bin/go-discord-bot artifacts/

            - run: echo "size=$(du -sb artifacts | cut -f 1)" >> $BASH_ENV
            - buildevents/add_context:
                field_name: artifacts_size_bytes
                field_value: $size
            
            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
                # taken to be the root directory of the workspace.
                root: artifacts
                # Must be relative path from root
                paths:
                  - go-discord-bot

  publish:
    machine: true
    steps:
      - buildevents/with_job_span:
          steps:
            - attach_workspace:
              # Must be absolute path or relative path from working_directory
              at: artifacts
              
            - run: ls -l
            - run: ls artifacts/ -l
            - run: echo "$ACR_PASSWORD" | docker login halbarad.azurecr.io -u $ACR_USER --password-stdin

            ## build the docker container
            #- run: |
            #    buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID docker_build -- \
            #    docker build . -t halbarad.azurecr.io/go/discord-bot:$CIRCLE_BRANCH
            #
            ### push the docker container to ACR
            #- run: |
            #    buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID docker_push -- \
            #    docker push halbarad.azurecr.io/go/discord-bot:$CIRCLE_BRANCH

workflows:
  build:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - watch:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      #- test:
      #    requires:
      #      - setup
      #    filters:
      #      tags:
      #        only: /.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          #filters:
          #  tags:
          #    only: /^v.*/
          #  branches:
          #    ignore: /.*/
